name: Sokoban
version: 0.0.0.1
license: MIT
data-dir: assets
data-files: sokoban_tilesheet.png

dependencies:
  - base
  - SFML

executables:
  sokoban:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -Wall
      - -Werror
